/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Basic health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed health check with system info */
        get: operations["getDetailedHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify/ic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify IC authenticity from image */
        post: operations["verifyIC"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify/results/{verification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get verification result by ID */
        get: operations["getVerificationResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get verification history */
        get: operations["getVerificationHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify/manufacturers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get supported manufacturers */
        get: operations["getManufacturers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video/sessions/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start video streaming session */
        post: operations["startVideoSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video/sessions/{session_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get video session status */
        get: operations["getVideoSessionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload and process image */
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasheets/fetch/{part_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch datasheet for part number */
        post: operations["fetchDatasheet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example healthy */
            status?: string;
            /** Format: date-time */
            timestamp?: string;
            service?: string;
            version?: string;
        };
        DetailedHealthResponse: components["schemas"]["HealthResponse"] & {
            database?: string;
            system?: {
                platform?: string;
                cpu_count?: number;
                memory_total_gb?: number;
                memory_available_gb?: number;
            };
        };
        VerificationResponse: {
            verification_id?: number;
            detected_part_number?: string;
            detected_manufacturer?: string;
            detected_text?: Record<string, never>[];
            confidence_scores?: {
                ocr?: number;
                logo?: number;
                font?: number;
            };
            logo_match_score?: number;
            font_similarity_score?: number;
            marking_accuracy_score?: number;
            overall_confidence?: number;
            is_genuine?: boolean;
            authenticity_reasons?: string[];
            analysis_results?: Record<string, never>;
            processing_time_seconds?: number;
        };
        VerificationResultDetail: {
            verification_id?: number;
            ic_id?: number;
            detected_part_number?: string;
            detected_manufacturer?: string;
            detected_text?: string;
            confidence_scores?: Record<string, never>;
            logo_match_score?: number;
            font_similarity_score?: number;
            marking_accuracy_score?: number;
            overall_confidence?: number;
            is_genuine?: boolean;
            authenticity_reasons?: Record<string, never>;
            analysis_results?: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
            processing_time_seconds?: number;
        };
        VerificationHistoryResponse: {
            total?: number;
            results?: {
                id?: number;
                part_number?: string;
                manufacturer?: string;
                is_genuine?: boolean;
                overall_confidence?: number;
                /** Format: date-time */
                created_at?: string;
            }[];
        };
        ManufacturersResponse: {
            manufacturers?: string[];
            details?: Record<string, never>;
        };
        VideoSessionResponse: {
            session_id?: string;
            status?: string;
            upload_url?: string;
            websocket_url?: string;
        };
        VideoSessionStatus: {
            session_id?: string;
            status?: string;
            /** Format: date-time */
            start_time?: string;
            /** Format: date-time */
            end_time?: string;
            duration_seconds?: number;
            frame_count?: number;
            device_id?: string;
            resolution?: string;
            fps?: number;
        };
        ImageUploadResponse: {
            image_id?: string;
            original_path?: string;
            processed_path?: string;
            metadata?: Record<string, never>;
            preprocessing_applied?: boolean;
            contrast_enhanced?: boolean;
        };
        DatasheetResponse: {
            success?: boolean;
            part_number?: string;
            manufacturer?: string;
            url?: string;
            local_path?: string;
            /** Format: date-time */
            downloaded_at?: string;
            processing_time_seconds?: number;
        };
        ErrorResponse: {
            detail?: string;
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getDetailedHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detailed health information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedHealthResponse"];
                };
            };
        };
    };
    verifyIC: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description IC image file
                     */
                    image_file?: string;
                    /** @description Known part number (optional) */
                    part_number?: string;
                    /** @description Known manufacturer (optional) */
                    manufacturer?: string;
                    /**
                     * @description Perform thorough verification including datasheet
                     * @default true
                     */
                    thorough_check?: boolean;
                };
            };
        };
        responses: {
            /** @description Verification complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVerificationResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResultDetail"];
                };
            };
            /** @description Result not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVerificationHistory: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                genuine_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationHistoryResponse"];
                };
            };
        };
    };
    getManufacturers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of manufacturers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManufacturersResponse"];
                };
            };
        };
    };
    startVideoSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    device_id?: string;
                    /** @default 1920x1080 */
                    resolution?: string;
                    /** @default 30 */
                    fps?: number;
                };
            };
        };
        responses: {
            /** @description Session started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoSessionResponse"];
                };
            };
        };
    };
    getVideoSessionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoSessionStatus"];
                };
            };
        };
    };
    uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                    /** @default true */
                    preprocess?: boolean;
                    /** @default false */
                    enhance_contrast?: boolean;
                };
            };
        };
        responses: {
            /** @description Image uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUploadResponse"];
                };
            };
        };
    };
    fetchDatasheet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                part_number: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    manufacturer?: string;
                    /** @default false */
                    force_refresh?: boolean;
                };
            };
        };
        responses: {
            /** @description Datasheet fetched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasheetResponse"];
                };
            };
        };
    };
}
